config/routes.rb
Rails.application.routes.draw do
  resources :products

<<<<<<< HEAD
   resources :articles do
   resources :comments
=======
  resources :articles do
  resources :comments

   root 'welcome#index'

>>>>>>> a98b3d826395d2c01520de359b795fa9b733cd18
end
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  def index
    @articles = Article.all
  end

  def show
  @article = Article.find(params[:id])
  end

  def new
  @article = Article.new
  end

  def edit
  @article = Article.find(params[:id])
  end

  def destroy
  @article = Article.find(params[:id])
  @article.destroy

  redirect_to articles_path
  end

  def create
  @article = Article.new(article_params)

  if @article.save
    redirect_to @article
  else
    render 'new'
  end
 end

def update
  @article = Article.find(params[:id])

  if @article.update(article_params)
    redirect_to @article
  else
    render 'edit'
  end
end

private
  def article_params
    params.require(:article).permit(:title, :text)
  end
    end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
<<<<<<< HEAD
	http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

=======
>>>>>>> a98b3d826395d2c01520de359b795fa9b733cd18
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <% if @article.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@article.errors.count, "error") %>  - Puede que el error al guardar este articulo sea por las siguientes razones:</h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :Articulo %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :Descripcion %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edicion del articulo</h1>

<%= render 'form' %>

<%= link_to 'Atras', articles_path %>

app/views/articles/index.html.erb
<h1>Listado de artículos</h1>

<%= link_to 'Nuevo Articulo', new_article_path %>

<table>
  <tr>
    <th>Articulo</th>
    <th>Descripcion</th>
    <th colspan="3"></th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.text %></td>
    <td><%= link_to 'Ver', article_path(article) %></td>
    <td><%= link_to 'Editar', edit_article_path(article) %><td><%= link_to 'Eliminar', article_path(article),
                    method: :delete, data: { confirm: 'Esta seguro que desea eliminar el articulo?' } %></td>
  </tr>
<% end %>
</table>

app/views/articles/new.html.erb
<h1> Nuevo Articulo </h1>

<%= render 'form' %>

<%= link_to 'Atras', articles_path %>

app/views/articles/show.html.erb
<p>
<<<<<<< HEAD
  <strong>Articulo:</strong>
=======
  <strong>Titulo:</strong>
>>>>>>> a98b3d826395d2c01520de359b795fa9b733cd18
  <%= @article.title %>
</p>

<p>
<<<<<<< HEAD
  <strong>Descripcion:</strong>
=======
  <strong>Texto:</strong>
>>>>>>> a98b3d826395d2c01520de359b795fa9b733cd18
  <%= @article.text %>
</p>

<h2>Comentarios</h2>
<%= render @article.comments %>

<<<<<<< HEAD
<h2>Añadir comentario:</h2>
<%= render "comments/form" %>

<%= link_to 'Volver al listado', articles_path %>
<%= link_to 'Editar articulo', edit_article_path(@article) %>
=======
<h2>Agregar un comentario:</h2>
<%= render "comments/form" %>

<%= link_to 'Editar Articulo', edit_article_path(@article) %> |
<%= link_to 'Volver a los articulos', articles_path %>
>>>>>>> a98b3d826395d2c01520de359b795fa9b733cd18

app/views/comments/_comment.html.erb
<p>
<<<<<<< HEAD
  <strong>Nombre:</strong>
=======
  <strong>Comentario:</strong>
>>>>>>> a98b3d826395d2c01520de359b795fa9b733cd18
  <%= comment.commenter %>
</p>

<p>
<<<<<<< HEAD
  <strong>Detalles:</strong>
=======
  <strong>Comentario:</strong>
>>>>>>> a98b3d826395d2c01520de359b795fa9b733cd18
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Eliminar comentario', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Esta seguro que desea eliminar el comentario?' } %>
</p>

app/views/comments/_form.html.erb
<<<<<<< HEAD
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :Nombre %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :Comentario %><br>
=======
%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
>>>>>>> a98b3d826395d2c01520de359b795fa9b733cd18
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/welcome/index.html.erb
<<<<<<< HEAD
<h1>Hola Rails..!!!!</h1>
<%= link_to 'My Blog', controller: 'articles' %>
=======
<h1>Holaaa, Railsss..!!! XD</h1>
<%= link_to 'Mi Blog', controller: 'articles' %>
>>>>>>> a98b3d826395d2c01520de359b795fa9b733cd18